#!/usr/bin/env python3
"""
gBGC paper — Figure 4: NR1 is the only disrupted coactivator LXXLL motif, despite many
sitting in comparably GC-rich regions.

Each point is one LXXLL ("NR box") motif from nine coactivators, plotted by its local GC
content in monotremes (x) against gene (y), coloured by status. Many motifs lie in GC-rich
regions (>60%), yet only NCOA1 NR1 is disrupted — high GC creates broad susceptibility while
the disruption that is retained is rare.

Reads: analysis/coactivator_scan/coactivator_lxxll_gc.csv (+ NR1 added manually, see note).
Outputs: figures/Fig4_gbgc.{png,pdf,svg}
"""
import matplotlib
matplotlib.use("Agg")
matplotlib.rcParams["svg.fonttype"] = "none"  # emit editable <text>, not glyph paths
matplotlib.rcParams["font.family"] = "sans-serif"
# Arial first (named in SVG; rendered locally via Liberation Sans, the metric-identical clone)
matplotlib.rcParams["font.sans-serif"] = ["Arial", "Liberation Sans", "Helvetica", "DejaVu Sans"]
import matplotlib.pyplot as plt
import csv
import sys
from pathlib import Path

PAPER = Path(__file__).resolve().parents[1]
OUT = Path(__file__).resolve().parent
COL_NR1 = "#E53935"
COL_OK = "#4CAF50"

# NR1 is plotted at its coding GC over the SAME ±15+5-codon window as every other motif in this
# figure (from the 48-species codon alignment, where NR1 aligns cleanly at a fixed column), so all
# points share one GC criterion. Computed, not hard-coded.
sys.path.insert(0, str(PAPER / "analysis" / "gbgc_genomic"))
from compute_reported_values import coding_nr1_gc_scanwindow  # noqa: E402


def load():
    # CSV is regenerated by analysis/coactivator_scan/build_coactivator_scan.py
    # (MAFFT-aligned, ±15 codons around each motif incl. the motif, platypus/echidna mean).
    rows = list(csv.DictReader(open(PAPER / "analysis" / "coactivator_scan" / "coactivator_lxxll_gc.csv")))
    out = []
    for r in rows:
        # The scan's NCOA1 LVQLL row is dropped: the coactivator scan's own per-gene MAFFT of the
        # restructured monotreme region is unreliable. NR1 is re-added below from the 48-species
        # codon alignment (where it aligns cleanly), using the same ±15+5-codon coding window.
        if r["gene"] == "NCOA1" and r["human_motif"] == "LVQLL":
            continue
        # EP300 LQNLL lies in a natively low-complexity (Pro/Ala-rich) region of p300; if a stray
        # alignment ever flags it disrupted, treat as intact. (Clean MAFFT already calls it intact.)
        status = r["status"]
        if r["gene"] == "EP300" and "PAP" in r["monotreme_motifs"]:
            status = "intact"
        # carry per-species GC so the dot can show a platypus↔echidna whisker
        pgc = float(r["platypus_GC"]) if r["platypus_GC"] else None
        egc = float(r["echidna_GC"]) if r["echidna_GC"] else None
        out.append((r["gene"], r["human_motif"], float(r["monotreme_local_GC"]), status, pgc, egc))
    # NR1 (NCOA1 LVQLL→PGQLP): coding GC over the same ±15+5-codon window as every other point,
    # from the 48-species alignment; dot at the platypus/echidna mean, whisker spanning the two.
    pgc = coding_nr1_gc_scanwindow("Ornithorhynchus_anatinus")
    egc = coding_nr1_gc_scanwindow("Tachyglossus_aculeatus")
    out.append(("NCOA1", "NR1 (LVQLL→PGQLP)", (pgc + egc) / 2, "disrupted", pgc, egc))
    return out


def main():
    data = load()
    genes = ["NCOA1", "NCOA2", "NCOA3", "NCOA6", "MED1", "NRIP1", "PPARGC1A", "EP300", "NCOA4"]
    gy = {g: i for i, g in enumerate(reversed(genes))}

    fig, ax = plt.subplots(figsize=(7.2, 4.6))
    # Every motif sits on its gene's exact y-row (no jitter — y is purely categorical).
    # The dot is the platypus/echidna MEAN; a thin whisker spans the two per-species values,
    # so between-monotreme variation is visible (invisibly small for most motifs, ~11 pts at NR1).
    # Where motifs share a GC value they overlap; semi-transparent fills let the density still read.
    for gene, mot, gc, status, pgc, egc in data:
        if gene not in gy:
            continue
        y = gy[gene]
        disrupted = status == "disrupted"
        # platypus↔echidna whisker (drawn first, behind the dot)
        if pgc is not None and egc is not None:
            ax.plot([min(pgc, egc), max(pgc, egc)], [y, y],
                    color=(COL_NR1 if disrupted else "#2E7D32"), lw=1.1, alpha=0.7,
                    solid_capstyle="round", zorder=(disrupted and 3) or 1)
        ax.scatter(gc, y, s=130 if disrupted else 55,
                   color=COL_NR1 if disrupted else COL_OK,
                   alpha=1.0 if disrupted else 0.55,
                   edgecolor="#333", linewidth=0.5, zorder=4 if disrupted else 2,
                   marker="X" if disrupted else "o")
        if disrupted:
            ax.annotate("NR1 — the only\ndisrupted motif", (gc, y),
                        xytext=(gc - 9, y - 1.1), fontsize=7, color=COL_NR1, fontweight="bold",
                        ha="center",
                        arrowprops=dict(arrowstyle="-", color=COL_NR1, lw=0.7))

    # faint horizontal guide per gene row, so the single-line-per-gene reading is clear
    for g, yy in gy.items():
        ax.axhline(yy, color="#EEEEEE", lw=0.6, zorder=0)

    # shade the "high GC" zone
    ax.axvspan(60, 90, color="#FFF3E0", alpha=0.5, zorder=0)
    ax.text(75, len(genes) - 1.0, "GC-rich (>60%):\nbroad susceptibility",
            fontsize=7, color="#8D6E00", ha="center", style="italic")

    ax.set_yticks(range(len(genes)))
    ax.set_yticklabels(list(reversed(genes)), fontsize=8)
    ax.set_xlabel("Local GC content in monotremes (%)", fontsize=9)
    ax.set_xlim(44, 90)
    ax.set_ylim(-0.7, len(genes) - 0.3)
    ax.set_title("Many coactivator LXXLL motifs are GC-rich, but only NR1 is disrupted",
                 fontsize=9.5, fontweight="bold")
    from matplotlib.lines import Line2D
    ax.legend(handles=[Line2D([0], [0], marker="o", color="w", markerfacecolor=COL_OK,
                              markeredgecolor="#333", markersize=8, label="intact in monotremes"),
                       Line2D([0], [0], marker="X", color="w", markerfacecolor=COL_NR1,
                              markeredgecolor="#333", markersize=11, label="disrupted in monotremes")],
              fontsize=7.5, loc="lower right", framealpha=0.95)
    ax.spines[["top", "right"]].set_visible(False)
    ax.tick_params(labelsize=8)
    ax.grid(axis="x", lw=0.3, alpha=0.3)

    for ext in ("png", "pdf", "svg"):
        fig.savefig(OUT / f"Fig4_gbgc.{ext}", dpi=300, bbox_inches="tight", facecolor="white")
    plt.close()
    print("Saved Fig4_gbgc (GC dimension)")


if __name__ == "__main__":
    main()
